#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef $(MY_MODULE_PATH)
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := guidriverCEGUIOgre
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  src/guceCEGUIOgre.cpp \
  src/guceCEGUIOgre_CButtonImp.cpp \
  src/guceCEGUIOgre_CCEGUIToGUCEFLogger.cpp \
  src/guceCEGUIOgre_CCheckboxImp.cpp \
  src/guceCEGUIOgre_CComboboxImp.cpp \
  src/guceCEGUIOgre_CEditboxImp.cpp \
  src/guceCEGUIOgre_CFileOpenDialogImp.cpp \
  src/guceCEGUIOgre_CFileSaveDialogImp.cpp \
  src/guceCEGUIOgre_CFileSystemDialogImp.cpp \
  src/guceCEGUIOgre_CFormBackendImp.cpp \
  src/guceCEGUIOgre_CGridViewImp.cpp \
  src/guceCEGUIOgre_CGUCECEGUIOGREModule.cpp \
  src/guceCEGUIOgre_CGUIDriver.cpp \
  src/guceCEGUIOgre_CImageFrameImp.cpp \
  src/guceCEGUIOgre_CInputCEGUIManipulator.cpp \
  src/guceCEGUIOgre_CLabelImp.cpp \
  src/guceCEGUIOgre_CListboxImp.cpp \
  src/guceCEGUIOgre_CMemoboxImp.cpp \
  src/guceCEGUIOgre_CMenuBarImp.cpp \
  src/guceCEGUIOgre_CPopupMenuImp.cpp \
  src/guceCEGUIOgre_CProgressBarImp.cpp \
  src/guceCEGUIOgre_CPushButtonImp.cpp \
  src/guceCEGUIOgre_CRenderContextImp.cpp \
  src/guceCEGUIOgre_CSpinnerImp.cpp \
  src/guceCEGUIOgre_CTabContentPaneImp.cpp \
  src/guceCEGUIOgre_CTabControlImp.cpp \
  src/guceCEGUIOgre_CTreeviewImp.cpp \
  src/guceCEGUIOgre_CVFSInfoProvider.cpp \
  src/guceCEGUIOgre_CWidgetImp.cpp \
  src/guceCEGUIOgre_CWindowImp.cpp \
  src/guceCEGUIOgre_OgreCEGUIRenderer.cpp \
  src/guceCEGUIOgre_OgreCEGUIResourceProvider.cpp \
  src/guceCEGUIOgre_OgreCEGUITexture.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/../../../GUCEF/trunk/common/include \
  $(MY_MODULE_PATH)/../../../GUCEF/trunk/gucefCOM/include \
  $(MY_MODULE_PATH)/../../../GUCEF/trunk/gucefCOMCORE/include \
  $(MY_MODULE_PATH)/../../../GUCEF/trunk/gucefCORE/include \
  $(MY_MODULE_PATH)/../../../GUCEF/trunk/gucefDRN/include \
  $(MY_MODULE_PATH)/../../../GUCEF/trunk/gucefGUI/include \
  $(MY_MODULE_PATH)/../../../GUCEF/trunk/gucefIMAGE/include \
  $(MY_MODULE_PATH)/../../../GUCEF/trunk/gucefINPUT/include \
  $(MY_MODULE_PATH)/../../../GUCEF/trunk/gucefMT/include \
  $(MY_MODULE_PATH)/../../../GUCEF/trunk/gucefPATCHER/include \
  $(MY_MODULE_PATH)/../../../GUCEF/trunk/gucefVFS/include \
  $(MY_MODULE_PATH)/../../../GUCEF/trunk/gucefVFS/plugins/vfspluginZIP/dependencies/zziplib \
  $(MY_MODULE_PATH)/../../../GUCEF/trunk/gucefVFS/plugins/vfspluginZIP/dependencies/zziplib/zzip \
  $(MY_MODULE_PATH)/../dependencies/Ogre/OgreMain/include \
  $(MY_MODULE_PATH)/../dependencies/Ogre/OgreMain/src \
  $(MY_MODULE_PATH)/../dependencies/Ogre/OgreMain/src/nedmalloc \
  $(MY_MODULE_PATH)/../dependencies/freetype/include \
  $(MY_MODULE_PATH)/../dependencies/freetype/include/freetype \
  $(MY_MODULE_PATH)/../dependencies/freetype/include/freetype/config \
  $(MY_MODULE_PATH)/../dependencies/freetype/include/freetype/internal \
  $(MY_MODULE_PATH)/../dependencies/freetype/include/freetype/internal/services \
  $(MY_MODULE_PATH)/../dependencies/freetype/src/winfonts \
  $(MY_MODULE_PATH)/../guceCORE/include \
  $(MY_MODULE_PATH)/../guceGUI/include \
  $(MY_MODULE_PATH)/dependency/CEGUI/dependencies/pcre \
  $(MY_MODULE_PATH)/dependency/CEGUI/include \
  $(MY_MODULE_PATH)/dependency/CEGUI/include/elements \
  $(MY_MODULE_PATH)/dependency/CEGUI/include/falagard


LOCAL_SHARED_LIBRARIES := \
  CEGUI \
  guceCORE \
  guceGUI

include $(BUILD_SHARED_LIBRARY)

