#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef $(MY_MODULE_PATH)
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := OgreMain
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  src/OgreAlignedAllocator.cpp \
  src/OgreAnimable.cpp \
  src/OgreAnimation.cpp \
  src/OgreAnimationState.cpp \
  src/OgreAnimationTrack.cpp \
  src/OgreArchiveManager.cpp \
  src/OgreAutoParamDataSource.cpp \
  src/OgreAxisAlignedBox.cpp \
  src/OgreBillboard.cpp \
  src/OgreBillboardChain.cpp \
  src/OgreBillboardParticleRenderer.cpp \
  src/OgreBillboardSet.cpp \
  src/OgreBone.cpp \
  src/OgreBorderPanelOverlayElement.cpp \
  src/OgreCamera.cpp \
  src/OgreCodec.cpp \
  src/OgreColourValue.cpp \
  src/OgreCommon.cpp \
  src/OgreCompositionPass.cpp \
  src/OgreCompositionTargetPass.cpp \
  src/OgreCompositionTechnique.cpp \
  src/OgreCompositor.cpp \
  src/OgreCompositorChain.cpp \
  src/OgreCompositorInstance.cpp \
  src/OgreCompositorManager.cpp \
  src/OgreConfigFile.cpp \
  src/OgreControllerManager.cpp \
  src/OgreConvexBody.cpp \
  src/OgreDataStream.cpp \
  src/OgreDDSCodec.cpp \
  src/OgreDefaultHardwareBufferManager.cpp \
  src/OgreDefaultSceneQueries.cpp \
  src/OgreDistanceLodStrategy.cpp \
  src/OgreDynLib.cpp \
  src/OgreDynLibManager.cpp \
  src/OgreEdgeListBuilder.cpp \
  src/OgreEntity.cpp \
  src/OgreException.cpp \
  src/OgreExternalTextureSource.cpp \
  src/OgreExternalTextureSourceManager.cpp \
  src/OgreFileSystem.cpp \
  src/OgreFont.cpp \
  src/OgreFontManager.cpp \
  src/OgreFreeImageCodec.cpp \
  src/OgreFrustum.cpp \
  src/OgreGpuProgram.cpp \
  src/OgreGpuProgramManager.cpp \
  src/OgreGpuProgramParams.cpp \
  src/OgreGpuProgramUsage.cpp \
  src/OgreHardwareBufferManager.cpp \
  src/OgreHardwareIndexBuffer.cpp \
  src/OgreHardwareOcclusionQuery.cpp \
  src/OgreHardwarePixelBuffer.cpp \
  src/OgreHardwareVertexBuffer.cpp \
  src/OgreHighLevelGpuProgram.cpp \
  src/OgreHighLevelGpuProgramManager.cpp \
  src/OgreImage.cpp \
  src/OgreInstancedGeometry.cpp \
  src/OgreKeyFrame.cpp \
  src/OgreLight.cpp \
  src/OgreLodStrategy.cpp \
  src/OgreLodStrategyManager.cpp \
  src/OgreLog.cpp \
  src/OgreLogManager.cpp \
  src/OgreManualObject.cpp \
  src/OgreMaterial.cpp \
  src/OgreMaterialManager.cpp \
  src/OgreMaterialSerializer.cpp \
  src/OgreMath.cpp \
  src/OgreMatrix3.cpp \
  src/OgreMatrix4.cpp \
  src/OgreMemoryAllocatedObject.cpp \
  src/OgreMemoryNedAlloc.cpp \
  src/OgreMemoryNedPooling.cpp \
  src/OgreMemoryTracker.cpp \
  src/OgreMesh.cpp \
  src/OgreMeshManager.cpp \
  src/OgreMeshSerializer.cpp \
  src/OgreMeshSerializerImpl.cpp \
  src/OgreMovableObject.cpp \
  src/OgreMovablePlane.cpp \
  src/OgreNode.cpp \
  src/OgreNumerics.cpp \
  src/OgreOptimisedUtil.cpp \
  src/OgreOptimisedUtilGeneral.cpp \
  src/OgreOptimisedUtilSSE.cpp \
  src/OgreOverlay.cpp \
  src/OgreOverlayContainer.cpp \
  src/OgreOverlayElement.cpp \
  src/OgreOverlayElementCommands.cpp \
  src/OgreOverlayManager.cpp \
  src/OgrePanelOverlayElement.cpp \
  src/OgreParticle.cpp \
  src/OgreParticleEmitter.cpp \
  src/OgreParticleEmitterCommands.cpp \
  src/OgreParticleIterator.cpp \
  src/OgreParticleSystem.cpp \
  src/OgreParticleSystemManager.cpp \
  src/OgrePass.cpp \
  src/OgrePatchMesh.cpp \
  src/OgrePatchSurface.cpp \
  src/OgrePixelCountLodStrategy.cpp \
  src/OgrePixelFormat.cpp \
  src/OgrePlane.cpp \
  src/OgrePlatformInformation.cpp \
  src/OgrePolygon.cpp \
  src/OgrePose.cpp \
  src/OgrePrecompiledHeaders.cpp \
  src/OgrePredefinedControllers.cpp \
  src/OgrePrefabFactory.cpp \
  src/OgreProfiler.cpp \
  src/OgreProgressiveMesh.cpp \
  src/OgrePVRTCCodec.cpp \
  src/OgreQuaternion.cpp \
  src/OgreRectangle2D.cpp \
  src/OgreRenderQueue.cpp \
  src/OgreRenderQueueInvocation.cpp \
  src/OgreRenderQueueSortingGrouping.cpp \
  src/OgreRenderSystem.cpp \
  src/OgreRenderSystemCapabilities.cpp \
  src/OgreRenderSystemCapabilitiesManager.cpp \
  src/OgreRenderSystemCapabilitiesSerializer.cpp \
  src/OgreRenderTarget.cpp \
  src/OgreRenderTexture.cpp \
  src/OgreRenderToVertexBuffer.cpp \
  src/OgreRenderWindow.cpp \
  src/OgreResource.cpp \
  src/OgreResourceBackgroundQueue.cpp \
  src/OgreResourceGroupManager.cpp \
  src/OgreResourceManager.cpp \
  src/OgreRibbonTrail.cpp \
  src/OgreRoot.cpp \
  src/OgreRotationSpline.cpp \
  src/OgreSceneManager.cpp \
  src/OgreSceneManagerEnumerator.cpp \
  src/OgreSceneNode.cpp \
  src/OgreSceneQuery.cpp \
  src/OgreScriptCompiler.cpp \
  src/OgreScriptLexer.cpp \
  src/OgreScriptParser.cpp \
  src/OgreScriptTranslator.cpp \
  src/OgreSearchOps.cpp \
  src/OgreSerializer.cpp \
  src/OgreShadowCameraSetup.cpp \
  src/OgreShadowCameraSetupFocused.cpp \
  src/OgreShadowCameraSetupLiSPSM.cpp \
  src/OgreShadowCameraSetupPlaneOptimal.cpp \
  src/OgreShadowCameraSetupPSSM.cpp \
  src/OgreShadowCaster.cpp \
  src/OgreShadowTextureManager.cpp \
  src/OgreShadowVolumeExtrudeProgram.cpp \
  src/OgreSimpleRenderable.cpp \
  src/OgreSimpleSpline.cpp \
  src/OgreSkeleton.cpp \
  src/OgreSkeletonInstance.cpp \
  src/OgreSkeletonManager.cpp \
  src/OgreSkeletonSerializer.cpp \
  src/OgreStaticGeometry.cpp \
  src/OgreStreamSerialiser.cpp \
  src/OgreString.cpp \
  src/OgreStringConverter.cpp \
  src/OgreStringInterface.cpp \
  src/OgreSubEntity.cpp \
  src/OgreSubMesh.cpp \
  src/OgreTagPoint.cpp \
  src/OgreTangentSpaceCalc.cpp \
  src/OgreTechnique.cpp \
  src/OgreTextAreaOverlayElement.cpp \
  src/OgreTexture.cpp \
  src/OgreTextureManager.cpp \
  src/OgreTextureUnitState.cpp \
  src/OgreUnifiedHighLevelGpuProgram.cpp \
  src/OgreUserObjectBindings.cpp \
  src/OgreUTFString.cpp \
  src/OgreVector2.cpp \
  src/OgreVector3.cpp \
  src/OgreVector4.cpp \
  src/OgreVertexIndexData.cpp \
  src/OgreViewport.cpp \
  src/OgreWindowEventUtilities.cpp \
  src/OgreWireBoundingBox.cpp \
  src/OgreWorkQueue.cpp \
  src/OgreZip.cpp \
  src/Threading/OgreDefaultWorkQueueStandard.cpp \
  src/nedmalloc/nedmalloc.c

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/src \
  $(MY_MODULE_PATH)/src/nedmalloc \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefIMAGE/plugins/imgpluginFreeImage/dependencies/FreeImage/Source \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefIMAGE/plugins/imgpluginFreeImage/dependencies/FreeImage/Source/DeprecationManager \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefIMAGE/plugins/imgpluginFreeImage/dependencies/FreeImage/Source/FreeImageToolkit \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefIMAGE/plugins/imgpluginFreeImage/dependencies/FreeImage/Source/LibJPEG \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefIMAGE/plugins/imgpluginFreeImage/dependencies/FreeImage/Source/LibMNG \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefIMAGE/plugins/imgpluginFreeImage/dependencies/FreeImage/Source/LibOpenJPEG \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefIMAGE/plugins/imgpluginFreeImage/dependencies/FreeImage/Source/LibPNG \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefIMAGE/plugins/imgpluginFreeImage/dependencies/FreeImage/Source/LibTIFF \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefIMAGE/plugins/imgpluginFreeImage/dependencies/FreeImage/Source/Metadata \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefIMAGE/plugins/imgpluginFreeImage/dependencies/FreeImage/Source/OpenEXR \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefIMAGE/plugins/imgpluginFreeImage/dependencies/FreeImage/Source/OpenEXR/Half \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefIMAGE/plugins/imgpluginFreeImage/dependencies/FreeImage/Source/OpenEXR/Iex \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefIMAGE/plugins/imgpluginFreeImage/dependencies/FreeImage/Source/OpenEXR/IlmImf \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefIMAGE/plugins/imgpluginFreeImage/dependencies/FreeImage/Source/OpenEXR/IlmThread \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefIMAGE/plugins/imgpluginFreeImage/dependencies/FreeImage/Source/OpenEXR/Imath \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefIMAGE/plugins/imgpluginFreeImage/dependencies/FreeImage/Source/ZLib \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefVFS/plugins/vfspluginZIP/dependencies/zlib \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefVFS/plugins/vfspluginZIP/dependencies/zziplib \
  $(MY_MODULE_PATH)/../../../../../GUCEF/trunk/gucefVFS/plugins/vfspluginZIP/dependencies/zziplib/zzip \
  $(MY_MODULE_PATH)/../../freetype/include \
  $(MY_MODULE_PATH)/../../freetype/include/freetype \
  $(MY_MODULE_PATH)/../../freetype/include/freetype/config \
  $(MY_MODULE_PATH)/../../freetype/include/freetype/internal \
  $(MY_MODULE_PATH)/../../freetype/include/freetype/internal/services \
  $(MY_MODULE_PATH)/../../freetype/src/winfonts


LOCAL_SHARED_LIBRARIES := \
  zlib \
  zziplib \
  FreeImage \
  freetype

include $(BUILD_SHARED_LIBRARY)

