#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef $(MY_MODULE_PATH)
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := MyGUI.Common
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  precompiled.cpp \
  Base/Ogre/BaseManager.cpp \
  Input/OIS/InputManager.cpp \
  Input/OIS/PointerManager.cpp \
  Ogre/RenderBox/RenderBoxScene.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH) \
  $(MY_MODULE_PATH)/Base \
  $(MY_MODULE_PATH)/BaseLayout \
  $(MY_MODULE_PATH)/Base/Ogre \
  $(MY_MODULE_PATH)/FileSystemInfo \
  $(MY_MODULE_PATH)/Input/OIS \
  $(MY_MODULE_PATH)/ItemBox \
  $(MY_MODULE_PATH)/Ogre/RenderBox \
  $(MY_MODULE_PATH)/PanelView \
  $(MY_MODULE_PATH)/../../../../../../GUCEF/trunk/gucefVFS/plugins/vfspluginZIP/dependencies/zziplib \
  $(MY_MODULE_PATH)/../../../../../../GUCEF/trunk/gucefVFS/plugins/vfspluginZIP/dependencies/zziplib/zzip \
  $(MY_MODULE_PATH)/../../../../dependencies/Ogre/OgreMain/include \
  $(MY_MODULE_PATH)/../../../../dependencies/Ogre/OgreMain/include/Android \
  $(MY_MODULE_PATH)/../../../../dependencies/Ogre/OgreMain/src \
  $(MY_MODULE_PATH)/../../../../dependencies/Ogre/OgreMain/src/nedmalloc \
  $(MY_MODULE_PATH)/../../../../dependencies/freetype/include \
  $(MY_MODULE_PATH)/../../../../dependencies/freetype/include/freetype \
  $(MY_MODULE_PATH)/../../../../dependencies/freetype/include/freetype/config \
  $(MY_MODULE_PATH)/../../../../dependencies/freetype/include/freetype/internal \
  $(MY_MODULE_PATH)/../../../../dependencies/freetype/include/freetype/internal/services \
  $(MY_MODULE_PATH)/../../../../dependencies/freetype/src/winfonts \
  $(MY_MODULE_PATH)/../MyGUIEngine/include


LOCAL_SHARED_LIBRARIES := \
  MyGUIEngine \
  OgreMain


LOCAL_LDLIBS := \
  -lMyGUI.OgrePlatform \
  -lOIS

include $(BUILD_SHARED_LIBRARY)

