#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef $(MY_MODULE_PATH)
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := CEGUI
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  src/CEGUIBase.cpp \
  src/CEGUIBoundSlot.cpp \
  src/CEGUIcolour.cpp \
  src/CEGUIColourRect.cpp \
  src/CEGUIConfig_xmlHandler.cpp \
  src/CEGUICoordConverter.cpp \
  src/CEGUIDataContainer.cpp \
  src/CEGUIDefaultLogger.cpp \
  src/CEGUIDefaultResourceProvider.cpp \
  src/CEGUIDynamicModule.cpp \
  src/CEGUIEvent.cpp \
  src/CEGUIEventArgs.cpp \
  src/CEGUIEventSet.cpp \
  src/CEGUIEventSignal.cpp \
  src/CEGUIEventSignalSet.cpp \
  src/CEGUIExceptions.cpp \
  src/CEGUIFactoryModule.cpp \
  src/CEGUIFont.cpp \
  src/CEGUIFontManager.cpp \
  src/CEGUIFontProperties.cpp \
  src/CEGUIFont_xmlHandler.cpp \
  src/CEGUIFreeTypeFont.cpp \
  src/CEGUIGlobalEventSet.cpp \
  src/CEGUIGUILayout_xmlHandler.cpp \
  src/CEGUIImage.cpp \
  src/CEGUIImageCodec.cpp \
  src/CEGUIImageset.cpp \
  src/CEGUIImagesetManager.cpp \
  src/CEGUIImageset_xmlHandler.cpp \
  src/CEGUILogger.cpp \
  src/CEGUIMouseCursor.cpp \
  src/CEGUIPixmapFont.cpp \
  src/CEGUIProperty.cpp \
  src/CEGUIPropertyHelper.cpp \
  src/CEGUIPropertySet.cpp \
  src/CEGUIRect.cpp \
  src/CEGUIRenderCache.cpp \
  src/CEGUIRenderer.cpp \
  src/CEGUIScheme.cpp \
  src/CEGUISchemeManager.cpp \
  src/CEGUIScheme_xmlHandler.cpp \
  src/CEGUIScriptModule.cpp \
  src/CEGUIScriptWindowHelper.cpp \
  src/CEGUISize.cpp \
  src/CEGUIString.cpp \
  src/CEGUISubscriberSlot.cpp \
  src/CEGUISystem.cpp \
  src/CEGUITexture.cpp \
  src/CEGUITextUtils.cpp \
  src/CEGUIWindow.cpp \
  src/CEGUIWindowFactory.cpp \
  src/CEGUIWindowFactoryManager.cpp \
  src/CEGUIWindowManager.cpp \
  src/CEGUIWindowProperties.cpp \
  src/CEGUIWindowRenderer.cpp \
  src/CEGUIWindowRendererManager.cpp \
  src/CEGUIXMLAttributes.cpp \
  src/CEGUIXMLHandler.cpp \
  src/CEGUIXMLParser.cpp \
  src/CEGUIXMLSerializer.cpp \
  src/elements/CEGUIBaseFactories.cpp \
  src/elements/CEGUIButtonBase.cpp \
  src/elements/CEGUICheckbox.cpp \
  src/elements/CEGUICheckboxProperties.cpp \
  src/elements/CEGUIClippedContainer.cpp \
  src/elements/CEGUICombobox.cpp \
  src/elements/CEGUIComboboxProperties.cpp \
  src/elements/CEGUIComboDropList.cpp \
  src/elements/CEGUIDragContainer.cpp \
  src/elements/CEGUIDragContainerProperties.cpp \
  src/elements/CEGUIEditbox.cpp \
  src/elements/CEGUIEditboxProperties.cpp \
  src/elements/CEGUIFrameWindow.cpp \
  src/elements/CEGUIFrameWindowProperties.cpp \
  src/elements/CEGUIGroupBox.cpp \
  src/elements/CEGUIGUISheet.cpp \
  src/elements/CEGUIItemEntry.cpp \
  src/elements/CEGUIItemEntryProperties.cpp \
  src/elements/CEGUIItemListBase.cpp \
  src/elements/CEGUIItemListBaseProperties.cpp \
  src/elements/CEGUIItemListbox.cpp \
  src/elements/CEGUIItemListboxProperties.cpp \
  src/elements/CEGUIListbox.cpp \
  src/elements/CEGUIListboxItem.cpp \
  src/elements/CEGUIListboxProperties.cpp \
  src/elements/CEGUIListboxTextItem.cpp \
  src/elements/CEGUIListHeader.cpp \
  src/elements/CEGUIListHeaderProperties.cpp \
  src/elements/CEGUIListHeaderSegment.cpp \
  src/elements/CEGUIListHeaderSegmentProperties.cpp \
  src/elements/CEGUIMenubar.cpp \
  src/elements/CEGUIMenuBase.cpp \
  src/elements/CEGUIMenuBaseProperties.cpp \
  src/elements/CEGUIMenuItem.cpp \
  src/elements/CEGUIMultiColumnList.cpp \
  src/elements/CEGUIMultiColumnListProperties.cpp \
  src/elements/CEGUIMultiLineEditbox.cpp \
  src/elements/CEGUIMultiLineEditboxProperties.cpp \
  src/elements/CEGUIPopupMenu.cpp \
  src/elements/CEGUIPopupMenuProperties.cpp \
  src/elements/CEGUIProgressBar.cpp \
  src/elements/CEGUIProgressBarProperties.cpp \
  src/elements/CEGUIPushButton.cpp \
  src/elements/CEGUIRadioButton.cpp \
  src/elements/CEGUIRadioButtonProperties.cpp \
  src/elements/CEGUIScrollablePane.cpp \
  src/elements/CEGUIScrollablePaneProperties.cpp \
  src/elements/CEGUIScrollbar.cpp \
  src/elements/CEGUIScrollbarProperties.cpp \
  src/elements/CEGUIScrolledContainer.cpp \
  src/elements/CEGUIScrolledContainerProperties.cpp \
  src/elements/CEGUIScrolledItemListBase.cpp \
  src/elements/CEGUIScrolledItemListBaseProperties.cpp \
  src/elements/CEGUISlider.cpp \
  src/elements/CEGUISliderProperties.cpp \
  src/elements/CEGUISpinner.cpp \
  src/elements/CEGUISpinnerProperties.cpp \
  src/elements/CEGUITabButton.cpp \
  src/elements/CEGUITabControl.cpp \
  src/elements/CEGUITabControlProperties.cpp \
  src/elements/CEGUIThumb.cpp \
  src/elements/CEGUIThumbProperties.cpp \
  src/elements/CEGUITitlebar.cpp \
  src/elements/CEGUITitlebarProperties.cpp \
  src/elements/CEGUITooltip.cpp \
  src/elements/CEGUITooltipProperties.cpp \
  src/elements/CEGUITree.cpp \
  src/elements/CEGUITreeItem.cpp \
  src/elements/CEGUITreeProperties.cpp \
  src/falagard/CEGUIFalagard_xmlHandler.cpp \
  src/falagard/CEGUIFalComponentBase.cpp \
  src/falagard/CEGUIFalDimensions.cpp \
  src/falagard/CEGUIFalFrameComponent.cpp \
  src/falagard/CEGUIFalImageryComponent.cpp \
  src/falagard/CEGUIFalImagerySection.cpp \
  src/falagard/CEGUIFalLayerSpecification.cpp \
  src/falagard/CEGUIFalNamedArea.cpp \
  src/falagard/CEGUIFalPropertyDefinition.cpp \
  src/falagard/CEGUIFalPropertyDefinitionBase.cpp \
  src/falagard/CEGUIFalPropertyInitialiser.cpp \
  src/falagard/CEGUIFalPropertyLinkDefinition.cpp \
  src/falagard/CEGUIFalSectionSpecification.cpp \
  src/falagard/CEGUIFalStateImagery.cpp \
  src/falagard/CEGUIFalTextComponent.cpp \
  src/falagard/CEGUIFalWidgetComponent.cpp \
  src/falagard/CEGUIFalWidgetLookFeel.cpp \
  src/falagard/CEGUIFalWidgetLookManager.cpp \
  src/falagard/CEGUIFalXMLEnumHelper.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/include/elements \
  $(MY_MODULE_PATH)/include/falagard \
  $(MY_MODULE_PATH)/../../../dependencies/freetype/include \
  $(MY_MODULE_PATH)/../../../dependencies/freetype/include/freetype \
  $(MY_MODULE_PATH)/../../../dependencies/freetype/include/freetype/config \
  $(MY_MODULE_PATH)/../../../dependencies/freetype/include/freetype/internal \
  $(MY_MODULE_PATH)/../../../dependencies/freetype/include/freetype/internal/services \
  $(MY_MODULE_PATH)/../../../dependencies/freetype/src/winfonts \
  $(MY_MODULE_PATH)/../../../dependencies/pcre


LOCAL_SHARED_LIBRARIES := \
  freetype \
  pcre

include $(BUILD_SHARED_LIBRARY)

